Repository balena-os/leviathan, pull requests merged in 2018-05, with the labels that each got.

#182 Visual fixes for semi-tests
  lib/main.js
  lib/utils.js
Labels: procbots/versionbot/no-checks

#184 Use contracts to get the arch version and led property of the device
  lib/main.js
Labels: procbots/versionbot/no-checks

#102 Add test to check image filename format
  CHANGELOG.md
  lib/components/resinio/sdk.js
  lib/main.js
  package.json
Labels: procbots/versionbot/ready-to-merge, test

#146 Produce, consume and format TAP output
  CHANGELOG.md
  entry.sh
  lib/main.js
  package.json
  scripts/format.js
Labels: procbots/versionbot/ready-to-merge

#190 Add pensieve backend to publish test results
  CHANGELOG.md
  Dockerfile
  Makefile
  entry.sh
  lib/main.js
  lib/utils.js
  package.json
  scripts/pensieve.js
Labels: procbots/versionbot/ready-to-merge

#194 Bugfixes
  entry.sh
  lib/components/resinio/sdk.js
  lib/main.js
  package.json
  scripts/format.js
  scripts/pensieve.js
  scripts/resolve.js
  scripts/teardown.js
Labels: procbots/versionbot/no-checks

#204 Fix pensieve output
  lib/main.js
  scripts/format.js
  scripts/pensieve.js
Labels: procbots/versionbot/no-checks

#207 Use API keys instead of authenticating with credentials
  CHANGELOG.md
  lib/components/resinio/sdk.js
  lib/main.js
  package.json
Labels: procbots/versionbot/ready-to-merge

#210 Split tests into their own files
  CHANGELOG.md
  Dockerfile
  lib/main.js
  package.json
  tests/bluetooth-test.js
  tests/device-online.js
  tests/enter-container.js
  tests/hdmi-uart5.js
  tests/hostapp-update.js
  tests/identification-led.js
  tests/kernel-splash-screen.js
  tests/os-file-format.js
  tests/push-container.js
  tests/push-multicontainer.js
  tests/reboot-with-app.js
  tests/reload-supervisor.js
  tests/resin-device-progress.js
  tests/resin-splash-screen.js
  tests/resin-sync.js
  tests/rpi-serial-uart0.js
  tests/rpi-serial-uart1.js
  tests/service-variables.js
Labels: procbots/versionbot/ready-to-merge
